version: '3'
services: 
    hugo:
        build:
            context: .
            dockerfile: ./.docker/hugo/Dockerfile
        volumes:
            - ".:/src"
        ports:
            - "1313:1313"
        tty: true
        working_dir: /src/blog
        command: hugo server --bind=0.0.0.0 -v

    php:
        container_name: blog-php
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/workspace
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /workspace/php
        tty: true
